name = "hello-hono"
compatibility_date = "2023-12-01"
main = "src/index.ts"

[vars]
TURSO_AUTH_TOKEN = ""
TURSO_DATABASE_URL = ""

[[kv_namespaces]]
binding = "NAMES_KV"
id = "51abe569feaa4eee937e919811352d1a"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"